[http]
port = 8080

[database]
url = "postgres://urussu:urussu@localhost:5432/urussu_v2?sslmode=disable"
swagger_path = "gen/openapiv2/urussu-be/v1/dots.swagger.json"

[log]
level = "info" # debug | info | warn | error
